[server]
headless = true
port = 8501
address = "localhost"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "dark"
primaryColor = "#1DB954"
backgroundColor = "#121212"
secondaryBackgroundColor = "#181818"
textColor = "#FFFFFF"
